Adds portable configuration possibility
bayleeadamoss/zazu pull request #144
Opened 2017-01-11 07:45 UTC by schmic

As discussed in #116 this adds the possibility to keep the configuration/plugins inside the application folder.

During startup this checks for a subdirectory called "portable" inside the cwd, if found that is used for storing configuration/plugins. Overrides ZAZU_HOME!

2017-01-11 08:01 UTC, schmic commented
Forgot to add `/portable` to .gitignore, please add after merge as well.

2017-01-11 17:16 UTC, blainesch commented
@schmic so what's the workflow? You open up the `.app` folder, create a `portable` folder and then run the app?

2017-01-12 12:43 UTC, schmic commented
@blainesch Exactly, if you want to use it portable simple create the "portable" folder.

2017-01-12 17:26 UTC, blainesch commented
I'm okay with merging this, but it should be documented somewhere. Maybe in the getting started section? Or maybe the download page since it has instructions for running it locally?

Can you add that to this pr?

2017-01-12 22:31 UTC, schmic commented
OK, gonna add the documentation into the PR tomorrow

2017-01-12 23:01 UTC, schmic commented
Docs added, hope that PR is still ok with the merge commit?

2017-01-12 23:01 UTC, bayleedev requested changes

2017-01-12 23:01 UTC, blainesch commented on docs/_documentation/configuration.md
> +Portable mode overrides ZAZU_HOME, if defined.
`ZAZU_HOME` isn't documented and was intended for testing purposes. I don't think we should mention it.

2017-01-12 23:01 UTC, blainesch commented on docs/_documentation/configuration.md
> +## Portable Mode {#portableMode}
I think this section should go at the bottom of the page.

2017-01-12 23:01 UTC, blainesch commented on docs/_documentation/getting-started.md
> +Zazu supports running in portable mode, details are found [here](/documentation/configuration#portableMode)
details are found on the [configuration page]

2017-01-12 23:01 UTC, blainesch commented on docs/_documentation/configuration.md
> +## Portable Mode {#portableMode}
I had no idea the `{#foo}` thing worked. I was using a js-shim. I should go back and fix that [:

2017-01-12 23:02 UTC, blainesch commented
I'll merge it in manually to get rid of the merge commit. You can rebase it away on this branch if you know how.

2017-01-12 23:08 UTC, schmic commented
There you go, no idea how to rebase though but that's fine.

2017-01-12 23:09 UTC, bayleedev approved these changes

2017-01-12 23:12 UTC, blainesch commented
I pushed your code to master:

https://github.com/tinytacoteam/zazu/commits/master

2017-01-12 23:12 UTC, closed without merging