Allow prefix to be more versatile.
bayleeadamoss/zazu pull request #154
Opened 2017-01-12 22:09 UTC by blainesch

This is just the failing test, not the code to fix it.

Expected:
I want a plugin that accepts both "weather" and "weather location". This is setup via a prefix script:
~~~ json
      {
        "id": "DefaultWeather",
        "type": "PrefixScript",
        "prefix": "weather",
        "space": true,
        "args": "Optional",
        "script": "weather.js",
        "connections": ["DarkSky"]
      },
~~~

The issue here is that this won't accept `weather` but instead `weather ` (with a space at the end).

My suggestion is that if `args` are optional and there are no arguments, the the space is also optional.

The workaround currently is to two prefix blocks:

~~~ json
      {
        "id": "DefaultWeather",
        "type": "PrefixScript",
        "prefix": "weather",
        "space": false,
        "args": "None",
        "script": "weather.js",
        "connections": ["DarkSky"]
      },
      {
        "id": "LocationWeather",
        "type": "PrefixScript",
        "prefix": "weather",
        "space": true,
        "args": "Required",
        "script": "weather.js",
        "connections": ["DarkSky"]
      }
~~~

Making this change will NOT break backwards compatibility, but it will reduce the number of required blocks.

2017-01-12 23:40 UTC, amjith approved these changes
I agree.

2017-01-29 20:34 UTC, blainesch commented
@amjith can you take a look?

2017-01-29 20:42 UTC, amjith requested changes
Functionally this PR does what it's supposed to do. I'm just curious about the regex matches.

2017-01-29 20:42 UTC, amjith commented on app/blocks/input/prefixScript.js
> +      if (this.args.match(/^r/i)) {
Is there a reason behind using `/^r/` instead of `/^required/`? 

Is it to protect against people misspelling the word 'Required' ?

2017-01-29 20:42 UTC, amjith commented on app/blocks/input/prefixScript.js
> +      } else if (this.args.match(/^o/i)) {
Same question but instead of `required` here this needs to be `optional`.

2017-01-29 20:46 UTC, blainesch commented on app/blocks/input/prefixScript.js
> +      if (this.args.match(/^r/i)) {
Exactly. They were all distinct enough this was fine. Do you think it should be more verbose?

2017-01-29 20:50 UTC, amjith commented on app/blocks/input/prefixScript.js
> +      if (this.args.match(/^r/i)) {
I'm totally in favor of code that is forgiving of user error. I'm just worried if the code is too obscure for future generations. I'm sure it's fine. I'll approve the PR and merge.

2017-01-29 21:16 UTC, amjith approved these changes

2017-01-29 21:16 UTC, merged