Height Mod Test
bayleeadamoss/zazu pull request #297
Opened 2017-06-27 18:06 UTC by Koolstr

Added height to config. Testing assigning height to a new var and using that to determine window height.

PR for issue: [](https://github.com/tinytacoteam/zazu-fallback/issues/8)

2017-06-29 16:27 UTC, bayleedev requested changes

2017-06-29 16:27 UTC, blainesch commented on app/lib/configuration.js
> +    this.height = 700
This should be 400

2017-06-29 16:27 UTC, blainesch commented on app/lib/configuration.js
>    load () {
Further down in this file we load and assign the `data` you need to setup `this.height = data.height || 400` or something similar.

2017-06-29 16:27 UTC, blainesch commented
Thank you for looking into it! This is a great start.

2017-06-29 20:37 UTC, Koolstr commented on app/lib/configuration.js
> +    this.height = 700
I intentionally set it to 700, since the purpose of this is to test if we can increase the window height, remember?

2017-06-29 20:52 UTC, Koolstr commented on app/lib/configuration.js
>    load () {
I presume you meant by this that I should be assigning `this.height = 700` in the load function, correct? I made a commit of exactly that now.

2017-06-29 20:55 UTC, Koolstr commented
No problem and thank you! Did you know? This is my first pull request I've ever made. :3 

So I don't understand how to do lots of things yet, but I'm learning.

2017-06-29 21:11 UTC, Koolstr reviewed
Read my comments on your suggestions.

2017-07-01 03:21 UTC, blainesch commented on app/lib/configuration.js
>    load () {
The number appears to work correctly on setting the height.

2017-07-03 17:59 UTC, Koolstr commented on app/lib/configuration.js
>    load () {
As in, with this compiled, you are seeing a difference in the height of the Zazu window? I tried it myself and did not notice anything different... :/

2017-09-06 03:22 UTC, blainesch commented
@Koolstr any update on this?

2018-02-21 02:06 UTC, Koolstr commented
What kind of update would there be? Looks like you made the changes needed and tried to merge it, but the tests failed? What still needs to be done to get those tests to pass?

2018-04-22 23:48 UTC, Koolstr commented
Has this been resolved, but the fix just isn't being merged due to build test failing? How can we ensure this passes?

2018-04-23 00:24 UTC, afaur commented
@Koolstr Thank you for your contribution to zazu. 

I looked at the local branch and added on a commit to your existing work. (https://github.com/tinytacoteam/zazu/commit/9630f11b169bc4bded557fdd47d611926de6f293#diff-2718248ecf9b3814c6e7fa23feb0a024R10)

It seems like max-height was being explicitly applied in `zazu-fixture` and caused any height alterations to not carry over to the results list ul. 

I just finished double checking the unit and cucumber tests and will be merging your work in to master soon.

2018-04-23 00:37 UTC, afaur commented
About to merge the PR open here:
https://github.com/tinytacoteam/zazu/pull/300#pullrequestreview-114221704

Going to close this one as all commits from @Koolstr will be kept and merged through that PR.

Thanks again for you work on this feature!

2018-04-23 00:37 UTC, closed without merging

2018-04-23 00:38 UTC, Koolstr commented
Awesome! Thank you for fully resolving this. And you are welcome. ^_^